title: Forqan Archive
description: Qur’an translation, Qur’an-by-Qur’an reflection, Qur’anic roots, and reflective articles in English and Farsi.
url: "https://forqan.co"
baseurl: ""

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

timezone: America/New_York

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en
      layout: post
      category: en

  - scope:
      path: "_posts/fa"
      type: posts
    values:
      lang: fa
      layout: post
      category: fa

  - scope:
      path: ""
    values:
      sitemap: true
